### ISSUE TITLE
Mobs not removing player from hatelist when player leaves zone

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#313]
Mobs not removing player from hatelist when player leaves zone. Noticed by Midgar.

**Comment by RaggyLP** [comment]
This also happens whilst the mob is been mezzed. Tested using Simple Mind, Simple Pleasures (ID 100439). Re-zoning places the player back on the hate list.

**Comment by portalerprk** [comment]
@RaggyLP  - when an NPC is mezzed.. does it *actually* wipe their hate list? or does it just suspend it?

**Comment by RaggyLP** [comment]
> @RaggyLP - when an NPC is mezzed.. does it _actually_ wipe their hate list? or does it just suspend it?

@portalerprk Seems the hate list *is* actually cleared as per the new .hate command.

![image](https://github.com/project-rubika/issues/assets/156821187/1596f774-b879-4280-8cb1-53b5d5db8bd9)

I also don't actually seem to be able to repo the situation of the hate list returning, even on rezoning with hostile nanos running on the target (Drains) and no mezz. Also tested with a low duration mezz to see if the hostile nanos would re-add to hate list and it doesn't, so it would appear that in one of the more recent merges, the root cause of the problem might've been fixed. I did notice that draining the target with a mezz active would place you on the hate list for about 1s~ before the mezz would reclear the hate list, which was something it actively wasn't doing before. So tentatively saying as of 10:05 UTC - 23/01/24 the bug is fixed.
