### ISSUE TITLE
Nanocasting does not get interupted correctly

### ISSUE THREAD

**Issue by sagstuen** [project-rubika/issues#356]
While casting a nano, jump will not interupt the casting, but the nano will complete sucessfully, with the correct message.
While casting a nano, moving will not interupt the casting, but you will get the "Nano program aborted" message, and the casting will continue until you zone.

Tested with Keeper's Edge on level 2 Keeper in Newland Backyard (Junkyard) 5

**Comment by portalerprk** [comment]
On live, it seems that jump does indeed "interrupt" casting.. but it actually still sends a "success message".

![image](https://github.com/project-rubika/issues/assets/60405799/d32b297a-4291-496f-bd8a-95df555880ed)

So I think we'll need to actually just "complete" the casting instead of aborting like we are now.

SITTING on the other hand seems to "abort" casting.

**Comment by portalerprk** [comment]
Should be fixed @sagstuen - please test in Notum
