### ISSUE TITLE
Level 25 players can not enter the Subway

### ISSUE THREAD

**Issue by sagstuen** [project-rubika/issues#365]
Can't enter subway at 25, max level atm is 24 to enter.

**Comment by prkdrake** [comment]
Pre-AI, the level cap on the subway was 24, rather than 25, so this isn't actually a bug, per se, but I do think we should change it to be 25 because it was probably a mistake FC made, it's probably better that it matches the nice round number of 25, and we're likely to see this bug report raised a few times if we close this as wontfix.

**Comment by prkdrake** [comment]
Patch has been applied, please test this and let us know if it's working

**Comment by TheTinkeringIdiot** [comment]
Fixed! I am able to enter the Subway at level 25, and not at level 26. Looks good!
