### ISSUE TITLE
Pets don't track moving targets (enemy or player)

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#492]
**Describe the bug**
Pets only seem to update their follow target every ten seconds or so. This applies whether the pet is following its owner or approaching a combat target. If the pet is given the attack or follow order it will update its target location immediately, but not again for 10 seconds (repeated commands keeps updating). If the follow or attack target moves before the pet gets there, the pet reaches the initial target location, then pauses for about 10 seconds before updating its target and again moving in pursuit. 

**To Reproduce**
1. Summon a pet
2. /pet follow. The pet moves to your location. 
3. Immediately move some distance away. The pet stays still. 
4. After about 10 seconds from its last movement, the pet will approach your position. 
5. Move some distance again. 
6. The pet will reach your previous position and pause for 10 seconds before again approaching you. 

**Expected behavior**
The pet should update the position of its target as that target moves. Ideally it would do this continuously, allowing the pet to reliably path toward its target.

**Comment by wowpin** [comment]
Found an interesting way of visualizing where the server 'thinks' a pet currently is while it's supposed to be following a player.

Here's a scenario:
1. Move away from the pet - most of the time it will stay stationary for some time before it follows.
2. Do **'/pet follow'** while the pet is still stationary.

/pet follow will do two things as far as I can see:
- It'll rubberband the pet to where the server thinks the pet should be - somewhere along the way from it's initial position towards toon position.
- It'll send the pet running towards owner

Interesting thing happens when you spam '/pet follow' - every time you do, it'll warp pet to a constantly updating server side pet position (I assume) - so that you can trace the progress it makes towards you.

**Comment by TheTinkeringIdiot** [comment]
Copied this info to #347 and closing as duplicate.
