### ISSUE TITLE
Instanced mobs don't leash back and wipe hate list

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#494]
**Describe the bug**
To avoid trains in instanced content, but live servers have some in-built limit to how far mobs will chase players, after which the mob drops its hate list and leashes back to it's normal location. That is not happening currently. Instanced mobs do eventually stop giving chase, after quite a long distance, but do not drop their hate list (combat never ends for the player) and do not leash back to their original locations. 

**To Reproduce**
1. Enter an instance (I used Subway)
2. With high run speed, blitz to the end
3. Be swarmed by many mobs that have follow you most of the way
4. Remain in combat until you either leave the instance or all mobs have been killed. 

**Expected behavior**
Mobs should give chase for a reasonable period, after which they leash back to their starting point and wipe their hate lists so combat can end for the player that ran by.

**Comment by RaggyLP** [comment]
Confirmed. Mobs do not leash back to initial starting locations after a set distance and the hatelist is not wiped. This could be a result of the lack of collision check too currently, combined with pathing update intervals.

![image](https://github.com/project-rubika/issues/assets/156821187/8e8da64c-9731-41ef-9d8c-efbf02274973)

**Comment by RaggyLP** [comment]
A further test in ToTW to ensure that this wasn't just some Z-level shenanigans. 

![image](https://github.com/project-rubika/issues/assets/156821187/300beeef-d8e0-4035-bf02-d551426fc458)

**Comment by RaggyLP** [comment]
Subway works beautifully now with the leashing and the hatelists getting wiped, has a bit of a problem area for the leashing navigation on the spiral stairway things tend to get stuck between chasing and returning. I assume this is due to the lack of LoS, but the rest of the place works 100%

ToTW has an interesting issue with the navmesh near DoT:

![image](https://github.com/project-rubika/issues/assets/156821187/15d531ce-4cd7-4cb7-b268-e1a82c01bd3b)
![image](https://github.com/project-rubika/issues/assets/156821187/76f6b960-5efd-464b-9fd9-9fb9cccef46b)

Middle corridor seems to result in a bundle of mobs, which are non-attackable.

GoT Leashes in his room as expected along with his robot friends. Gartua is on a room leash, he shouldn't be, but honestly, it's such a minor issue.

![image](https://github.com/project-rubika/issues/assets/156821187/bdbcf697-c081-442a-87e6-b1b9faef712c)

Lien and firends can get jammed here when returning.

Overall, this system is fantastic, with just a few edge cases that need ironing out.

**Comment by TheTinkeringIdiot** [comment]
Concur with Raggy's findings, mobs in instances appear to be leaching back to their spawn points and wiping their hate lists as expected.
