### ISSUE TITLE
Most SL mobs do not give shadowknowledge

### ISSUE THREAD

**Issue by AOFlux** [project-rubika/issues#504]
**Describe the bug**
Most mobs in Penumbra/Inferno/Pandemonium do not give shadowknowledge upon killing them.

The exceptions I've encountered so far are:
Hecklers of life
Spirit hunters
Various spirit mobs
Various stalker mobs

The inferno/penumbra dyna bosses as well as subjugators do no give shadowknowledge at all.

This is for LVL200+ characters.
Pre-200, all mobs give regular XP.

**To Reproduce**
1. Log into a lvl 200-219 character
2. Go to any dyna camp in inferno
3. Kill the dyna boss and the mobs - they should not give xp, with the exceptions mentioned above.

**Comment by reneraen** [comment]
Could you please add /getall when reporting things like not getting SK from all mobs? 

The steps in bug form is needed to reproduce the bug(s) better. SK has quite a lot of “ties” to it. Like faction, side, acceptance of progressing above 200 to enable sk is set etc. if that is not set on your character the bug might be the opposite way around that the bug is that you are getting sk while you shouldn’t get it

**Comment by RaggyLP** [comment]
After a run around Inferno murdering anything on sight, I can confirm that everything in level range now gives SK. This was likely solved with the move to 18.4. Closing as fixed as of 31/08/2024.
