### ISSUE TITLE
Targeting a guard while casting a self-only Adventurer morph causes the player to be PVP flagged

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#666]
**Describe the bug**
Adventurer morphs have no external effects and are self-only nanos. However, targeting a guard while casting a morph nano causes the player to become flagged for PVP. Guards remain passive, though whether this is because they are not suffering an attack, or because they simply never attack anything (#415) is unknown. 

**To Reproduce**
1. Be an Adventurer
2. Target a guard
3. Cast any morph
4. You are now flagged

**Expected behavior**
Self only nanos should not count as a hostile action for purposes of PVP flagging. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/bed812e9-9838-4538-999e-63b1cd95d6e4)

**Comment by RaggyLP** [comment]
Confirmed. However this doesn't seem to be limited to just Advy Morphs and seems to affect any nano that would otherwise be a self cast.

![image](https://github.com/project-rubika/issues/assets/156821187/bb1fe58e-c762-4969-b34c-bdc2c5533be6)
![image](https://github.com/project-rubika/issues/assets/156821187/de58992b-7602-4eec-b0c2-4356e08979a2)
![image](https://github.com/project-rubika/issues/assets/156821187/dfd9fda8-58d9-4fa7-a3b6-dc98b296b9c0)
![image](https://github.com/project-rubika/issues/assets/156821187/ab5cb221-76b6-4bbd-83a1-89048a6bab00)

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/ab75dedc-5f7e-4703-a344-c885ac61a8fb)
![image](https://github.com/user-attachments/assets/c3cd5865-256f-4c04-b3bc-312307122d1f)

This appears to now be semi-fixed. Attempting to cast a self-only nano on a target now reports that the target cannot be attacked instead of actively flagging the user, but doesn't actively cast to the self. At least it's not flagging you now though! Closing this specific instance as fixed for now. 25/07/24.
