### ISSUE TITLE
NPCs archtype using nanos beyond their level.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#686]
**Describe the bug**
Certain mission NPCs are hitting for more than their intended values and casting nanos otherwise out of range for that level.

**To Reproduce**
1. Roll and enter a low level mission
2. Notice casts from mobs being higher than intended level values

**Expected behavior**
Mission NPCs should respect mission level and cast nanos relevant to the values for that range.

Please add any further NPC instances below with the following information:

```
NPC Name:
NPC Level:
NPC Nano Cast:
Mission Level:
```

**Comment by kewlgui1** [comment]
NPC Name: Soft Nanogun
NPC Level: 12 
NPC Nano Cast: Unknown but delt poison Damage
Mission Level: 12
![image](https://github.com/project-rubika/issues/assets/165961204/92e85d5c-1901-4f20-a375-6e81e6545eba)

**Comment by GlitchyGirl** [comment]
Got a few things here to report :

Reporting a Rookie Functionary that just nuked me into high orbit with an attack that did 1445 melee damage (not sure what ability it used)

![image](https://github.com/project-rubika/issues/assets/43483963/b8bcdbaa-4a02-426c-974e-651a8d10d064)
----

Level 17 virus builder nuked me for 346 fire damage

![image](https://github.com/project-rubika/issues/assets/43483963/6669258f-6aa7-46cd-b295-045241df5776)
----

Level 17 soft informer casting full hp heals on themselves lol
Can't quite tell what nanos are going off via fight target ncu or nanotarget ncu since that doesnt report :>

![image](https://github.com/project-rubika/issues/assets/43483963/4c888db8-4b6c-474b-9746-b7d1228af2a0)

----
Level 17 rookie dealer tried to cast a health haggler ability of some sort, on itself so it killed itself with it's heal xD

----
Well that's a new one Soft informer cast a wide area snare, and hit the other npc in the room.  A soft crook.  So soft crook killed soft informer lol.

----
Another level 17 rookie dealer suicided itself with a health haggler type ability lol
----

Level 18 Novice virus builder just cast biotoxin MK4 on me lol. 
![image](https://github.com/project-rubika/issues/assets/43483963/f03718fe-bf7c-47dd-9cd5-e809af70764a)

----
Soft Clan diversionist (level 18) killed me via Delayed Assassin.

----

**Comment by RaggyLP** [comment]
Linked to #695.

![image](https://github.com/project-rubika/issues/assets/156821187/20f57c70-1c74-4502-8690-b5872c0a9482)

This appears to be an issue with the NPC archtype that is generated with [Rank] [Side] [Profession] names and isn't limited to Missions. Merging tickets with a focus on this here.

**Comment by GlitchyGirl** [comment]
NPC name: Rookie functionary
NPC level 18
Mission level 24 
Ability Cast: Inhibit motion (high level crat snare)

**Comment by RaggyLP** [comment]
Tested with a variety of levels of the above mob archtypes. Level 5s now only cast very relevant nanos and higher (110+) now have a range which makes sense for their level. Closed as fixed as of 25/07/24.
