### ISSUE TITLE
NPCs not spawning - Camelot Castle

### ISSUE THREAD

**Issue by TarasqueAO** [project-rubika/issues#716]
**Describe the bug**
Morgan Le Faye is missing/invisible 
I receive debuff and take dmg but no visual mob inside.
Edit: from debug i get this:
[11:48:22][Kungfu] Damage: 326 on Kungfu with CamelotMorganLeFey1_001 (Override: CamelotMorganLeFey1_001)

**To Reproduce**
1. Go to Camelot castle or /teleport 162 160 y 23 120
2. Observe no Morgan but you get the "enslaved" debuff and something is hitting you.

**Expected behavior**
Morgan Le Faye should be in this room at Camelot Castle unless killed.
Tried different toons on different days etc but always same behavior.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/166374747/9f7b1a08-0ee6-438a-8f51-7734a7b23a01)

**Playfield info:**

```
Extended location information:
- 161.8, 160.3, 22.4 (161.8 160.3 y 22.4 120)
- Pf Proxy: Model=51100:120 GS=0 SG=0 R=120, resource: 120
- zone: 22, area: "FIGHT"
Server id: 1, character id: 50000:1479, time: 2024-04-08 11:34:41 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by JulianVallee** [comment]
+1, also couldn't find her the one time I've been there

**Comment by RaggyLP** [comment]
![image](https://github.com/project-rubika/issues/assets/156821187/5dca67a7-e7c4-44bb-9e40-6fe823f53907)

Confirmed that she is physically present within the PF at her assigned co-ordinates and attacks as expected, however, is not rendered and cannot be attacked or killed.

**Comment by prkdrake** [comment]
This is likely fixed, please re-check this and update the ticket.

**Comment by RaggyLP** [comment]
Not able to confirm, there is a current issue where *everything* in Camelot seems to not be spawning.

**Comment by kajoriEU** [comment]
Looking good currently, this issue seems to be fixed.

![{EA822DDD-2DE7-4003-8234-F6958B331377}](https://github.com/user-attachments/assets/708ca306-2c48-4d2d-8cfa-d5efd23134b3)

![{CED0C13F-2F3D-4A59-BC68-5D3BB625EA11}](https://github.com/user-attachments/assets/4102c173-f00f-4616-acc1-127277263062)

![{4626F1B7-294B-4140-9D0C-EC03CBA2FE54}](https://github.com/user-attachments/assets/2d6d3946-2a14-49eb-a64f-0d4c88efe87b)

Tara also there but killed it before I could take a picture :p sry
