### ISSUE TITLE
Test of Psychic - The Faithful - Young Silvertail doesn't open chat dialogue. [SL Start]

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#802]
### Reproduction steps

```bash
1. After speaking with El-Domo, the Forest Ranger and getting Test of Psychic - The Faithful (U9MF), talk to the Young Silvertail `.tp 508.5 341.9 y 44.2 4313`
2. `Young Silvertail: {/text This creature looks absolutely terrified.}` - is output to the vicinity.
```

### Expected results

```bash
Talking to the Young Silvertail should open conversation options to trade it the Rag (223764) and update the quest.
```

### Actual results

```bash
`Young Silvertail: {/text This creature looks absolutely terrified.}` - is output to the vicinity.
```

### Bug prevalence

Every time.

### Description

```bash
Prior to the Blabot integration, the Young Silver tail had a diagolue window, however did not accept the Rag as a trade to allow the quest to proceed.
```

### Report link

N/A

**Comment by kajoriEU** [comment]
![{82673F84-940F-4E17-B594-4A3B60741FE9}](https://github.com/user-attachments/assets/56a2e1ec-029c-44ee-b591-8b6420ed6c97)

If you left click the Rag and put it on the Young Silvertail (Left clicking the Rag and right clicking the Young Silvertail with the Rag on the cursor) the mission updates.

![{EDF6A88A-2715-44B3-B4F9-1A86EA7B7E49}](https://github.com/user-attachments/assets/c5c7a9b3-fd16-42dc-8e42-0b1206c055d7)

Upon completing the Clan / Faithful mission of this side it rewards you with a Bracer of Strength which is the wrong reward, which should be Ring of Enhanced Psychic (ItemID 223769 QL1) instead. The player also keeps the Omni / Chosen side of this mission which is not expected behavior as it usually only lets you finish one quest and not both.

**Comment by prkdrake** [comment]
I've looked into this quest - you just need to use the rag on the silvertail. The silvertail does not have any questions, texts or trades, though it does have a few stock phrases, none of which is working correctly - though this quest is actually possible to complete, so I suggest it should be closed for now and someone can recreate the issue about the silvertail's stockphrases later if they wish

**Comment by prkdrake** [comment]
This should be fixed by the latest update.
