### ISSUE TITLE
AOE Nukes do not deal damage

### ISSUE THREAD

**Issue by donkeyohtay** [project-rubika/issues#835]
### Reproduction steps

```bash
1. Target an enemy
2. Cast an AOE nuke (tested with Brief Poison Fog and Radiation Pulse)
3.
```

### Expected results

```bash
Damage is dealt in an area around target, aggroing target and other enemies hit.
```

### Actual results

```bash
Nanos are cast successfully but do not deal damage. Targeted enemy is aggroed but does not take damage. Enemies nearby are not damaged and not aggroed.
```

### Bug prevalence

Every cast

### Description

```bash
I had just logged in and attempted to aoe mobs in the subway, and noticed immediately that it wasn't dealing damage. Logged out and back in, no change. Zoned to outdoors, no change. Logged outdoors and no change. Restarted client, still no change.
```

### Report link

https://pastebin.com/Z3hQnFQr

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/65c3435f-03b9-4cc4-9159-3800ace9c046)

Confirmed, AoE nukes currently have no effect, neither

**Comment by 7RO11** [comment]
aoe nukes are doing damage once again but...

![Screenshot from 2024-09-07 17-06-21](https://github.com/user-attachments/assets/98841f3e-d07b-4d30-b8f1-f156dfa317d3)
enemies who cast them damage other enemies in the area
on some further testing with .get health on mobs in the area, aoe nukes don't seem to actually lower their health 

![Screenshot from 2024-09-07 17-07-30](https://github.com/user-attachments/assets/1e84d05b-f47a-4c06-a2f2-0618dde09ed8)
casting aoe nukes on yourself does damage to yourself
this also to apply to mobs, so mobs that cast them will kill themselves if you fight them long enough

on a positive note the crashing caused by mobs using aoe nukes/spells in #751 seems to be fixed

**Comment by donkeyohtay** [comment]
Looks like while killing mobs in deep subway, the AOE nuke (tested with Brief Poison Fog) is hitting the targeted mob twice instead of once.

**Comment by portalerprk** [comment]
@7RO11 - try your noted issues again. I *think* I should have them resolved.

**Comment by donkeyohtay** [comment]
Seems to be fixed to me

**Comment by 7RO11** [comment]
casting aoes on self no longer damages self.

i was unable to confirm the other issue with enemies hitting enemies since the incomplete rebuilds are no longer casting aoe nukes, at least in the 30 minutes i let them hit me. they did cast their aoe debuff, mass claw eye, and it didn't effect other enemies. 

also aoe nukes only hit once when targeting an enemy ☑️
