### ISSUE TITLE
Engineer pet's health regeneration is low

### ISSUE THREAD

**Issue by Nephima** [project-rubika/issues#871]
**Describe the bug**
Engineer's pet, as I remember on live server, had a quicker health regeneration when out of combat. I believe it was percentage based or stat based, resulting in regeneration to be around (wild guess) 0.5% health per second or so. But here I feel the heal delta is just either copied from my character's heal delta (6 hit points every 25 seconds) or based on some stat of the pet? Anyway it's too low and pet is technically without self-healing after battles which forces the user into re-casting the pet often.

**To Reproduce**
1. Spawn pet as an Engineer.
2. Use it in battle to get it to low health.
3. Observe the speed of the pet's health regeneration.

**Expected behavior**
Engineer's pet heal regeneration should be much quicker.

**Screenshots**
n/a

**Character info:**
Character name: Telca

**Playfield info:**

Extended location information:
- 388.7, 340.7, 0.2 (388.7 340.7 y 0.2 545)
- Pf Proxy: Model=51100:545 GS=0 SG=0 R=545, resource: 545
- zone: 169, area: "West Athen"
Server id: 1, character id: 50000:2379, time: 2024-09-09 12:52:20 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.
----

**Comment by kajoriEU** [comment]
>  I feel the heal delta is just either copied from my character's heal delta (6 hit points every 25 seconds) ...

I tested if the players healdelta is mimiced by the pet and I could not get the pet to do that so that does not seem to be the case.

> pet is technically without self-healing after battles which forces the user into re-casting the pet often

With the current biggest RK Pet healing only for 9 points per healdelta tick, you might be right on that the healdelta is low compared to that of current live but we need some reference of how it used to be because I know that pet profs got their pets buffed a few years ago.

**Comment by kajoriEU** [comment]
It just works 👍 . Fixed as of 11/09/2024
