### ISSUE TITLE
Spec books cant be turned in

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#888]
### Reproduction steps

```bash
1.  Talk to Professor Dedlock at IPS basic
2.  Trade opens
3.  You can attack him if you're bored, he doesnt hit that hard
```

### Expected results

```bash
A chat window should open that allows you to trade him and whatnot
```

### Actual results

```bash
Trade opens
```

### Bug prevalence

Every time

### Description

```bash
Oddly enough, suppression gas is at 100%.  and you can attack vendors too.
```

### Report link

https://pastebin.com/0kUuqs9w

**Comment by kajoriEU** [comment]
I can not reproduce this behavior currently and Dedlock **seems** to be working as expected.

![{E85D26BA-F376-47DC-82F3-6703819B1FF5}](https://github.com/user-attachments/assets/b9481528-47e3-4a49-931c-7cf6d649252e)

**Comment by kajoriEU** [comment]
This could be connected to a different issue #333 . When entering a PF for the first time after it has been empty for a while, you may need to rezone or relog for the NPCs to spawn correctly or to correct their behavior (such as getting them to initiate dialogue instead of opening trade window.)

I will open a seperate issue for him being attackable.
