### ISSUE TITLE
items aren't added to overflow inventory

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#959]
### Reproduction steps

```bash
1. spawn a piece of living cyber armor .item 163422 163422 1
2. right click it with a full inventory so that it levels up
```

### Expected results

```bash
the item to be added to overflow inventory
```

### Actual results

```bash
no item is added to overflow inventory
```

### Bug prevalence

everytime

### Description

```bash
mission rewards added to inventory have the same behavior 
tradeskilling with a full inventory will say "no available space in inventory"
```

### Report link

https://pastebin.com/matz1Bds

**Comment by kajoriEU** [comment]
Confirmed. 👍

When right-clicking levelable items, they currently disappear from the inventory and do not appear in the 'Overflow' inventory.

Chat displays `Your inventory overflowed! Get the items before leaving the area or they will be deleted.` correctly

![{012403AA-08AA-4C21-8944-6A7A72187421}](https://github.com/user-attachments/assets/e5cb5803-2b45-4469-90a5-f4bb5248b991)

![{EF7CA345-0853-4700-8E09-3FB90593D94E}](https://github.com/user-attachments/assets/b52de00e-74b6-435e-93d2-325addf29639)

#### 

This was fixed just a few days ago with #433 but since then became an issue again.

**Comment by prkdrake** [comment]
Should be fixed now

**Comment by 7RO11** [comment]
confirmed fixed 9/26/24, items from mission rewards or rmb-ing leveling items are added to overflow
